修改为“第n名”
qianjunakasumi/ZhiXueRank pull request #8
Opened 2024-01-02 16:22 UTC by Anyayay

![image](https://github.com/qianjunakasumi/ZhiXueRank/assets/37764175/77e2b10e-c312-42b6-bd54-0184bea7f920)

2024-01-08 01:17 UTC, qianjunakasumi commented
建议增加“第”字左边和学科名称之间的间距

2024-01-08 01:17 UTC, qianjunakasumi requested changes
建议增加“第”字左边和学科名称之间的间距

2024-01-08 04:39 UTC, Anyayay commented
> 建议增加"第"字左边和学科名称之间的间距

抱歉，我目前没有可修改的环境，需要等到周末，或者你先改一下？

2024-01-08 07:18 UTC, qianjunakasumi commented
> 抱歉，我目前没有可修改的环境，需要等到周末，或者你先改一下？

你可在周末进行修改工作 😀

2024-01-13 06:07 UTC, Anyayay commented
抱歉 先不要合并 我刚刚没注意到你这几天提交了一个新的 我晚些时候会重新开一个pr的

2024-01-13 06:35 UTC, qianjunakasumi commented
> 抱歉 先不要合并 我刚刚没注意到你这几天提交了一个新的 我晚些时候会重新开一个pr的

您也可以新提交一个 commit 来撤销不相关（主分支上）的修改，我通过 squash 合并即可

2024-01-13 09:54 UTC, Anyayay commented
或许已经可以 我在这方面还才疏学浅 麻烦您了

2024-01-13 12:21 UTC, qianjunakasumi approved these changes

2024-01-13 12:21 UTC, qianjunakasumi commented
感谢你对项目的贡献

2024-01-13 12:22 UTC, merged